CREATE TABLE CMF_SEQUENCE_WORKER_NODE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LAUNCH_DATE DATE NOT NULL COMMENT 'launch date',
  LIFE DATETIME DEFAULT NULL,
  PRIMARY KEY(ID)
) COMMENT='DB WorkerID Assigner for UID Generator',ENGINE = INNODB DEFAULT CHARSET=utf8;